services:
  app:
    build:
      context: .
    restart: always
    environment:
      REDIS_URL: redis://redis:6379/0
      SECRET_EXPIRY: "604800"
      STORAGE_TYPE: redis
      Password: ${PASSWORD}
    healthcheck:
      test: "curl -f http://localhost:3000"
      interval: 10s
      timeout: 5s
      retries: 5
    depends_on:
      - redis
    networks:
      - immich-internal
      - global-proxy-network
  redis:
    image: redis:alpine
    restart: always
    volumes:
      - ./data:/data      
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - immich-internal
networks:
  global-proxy-network:
    external: true
  immich-internal:
    internal: true
